export type Charity = {
  slug: string;
  name: string;
  category: string;
  status: "Active" | "Completed";
  shortDescription: string;
  whatTheyDo: string;
  whoTheyHelp: string;
  whySelected: string;
  impactExample: string;
  sdgs: string[];
  amountRaised: number;
  ceiling: number;
  registration: string;
  yearsActive: number;
  verificationNotes: string;
};

// Dummy data for the static prototype. No figures here represent real funds raised;
// the final charity list, registration details, and ceilings are still to be confirmed.
export const charities: Charity[] = [
  {
    slug: "unicef",
    name: "UNICEF",
    category: "Children",
    status: "Active",
    shortDescription:
      "Supports children with health, nutrition, education, protection, and emergency relief programs.",
    whatTheyDo:
      "Delivers health, nutrition, education, protection, and emergency-relief programs for children worldwide.",
    whoTheyHelp: "Children and families affected by poverty, conflict, disaster, and limited access to services.",
    whySelected: "Long-standing global reach, transparent reporting, and strict child-protection standards.",
    impactExample: "Contributions of this kind have helped fund vaccination drives and emergency nutrition support.",
    sdgs: ["SDG 3", "SDG 4", "SDG 10"],
    amountRaised: 312000,
    ceiling: 500000,
    registration: "Registered international NGO",
    yearsActive: 75,
    verificationNotes: "Verified via public annual reporting and international governance standards.",
  },
  {
    slug: "wwf",
    name: "WWF",
    category: "Environment",
    status: "Active",
    shortDescription: "Conserving nature and reducing the most pressing threats to the diversity of life on Earth.",
    whatTheyDo: "Runs conservation, habitat protection, and climate-focused environmental programs.",
    whoTheyHelp: "Wildlife populations, natural habitats, and communities affected by environmental change.",
    whySelected: "Established environmental credibility and clear, measurable conservation outcomes.",
    impactExample: "Supports habitat restoration and species-protection projects across multiple regions.",
    sdgs: ["SDG 13", "SDG 14", "SDG 15"],
    amountRaised: 184000,
    ceiling: 500000,
    registration: "Registered international NGO",
    yearsActive: 60,
    verificationNotes: "Verified via public annual reporting and independent conservation audits.",
  },
  {
    slug: "medecins-sans-frontieres",
    name: "Medecins Sans Frontieres",
    category: "Health",
    status: "Active",
    shortDescription: "Delivering emergency medical care to people affected by conflict, disease, and disaster.",
    whatTheyDo: "Provides emergency and ongoing medical care in crisis and under-served settings.",
    whoTheyHelp: "People affected by conflict, epidemics, natural disasters, and limited healthcare access.",
    whySelected: "Independent medical-relief track record and strict neutrality principles.",
    impactExample: "Contributions of this kind have supported emergency medical teams and mobile clinics.",
    sdgs: ["SDG 3"],
    amountRaised: 421000,
    ceiling: 500000,
    registration: "Registered international NGO",
    yearsActive: 50,
    verificationNotes: "Verified via public annual reporting and independent financial audits.",
  },
  {
    slug: "save-the-children",
    name: "Save the Children",
    category: "Children",
    status: "Active",
    shortDescription: "Helps children access education, healthcare, protection, and emergency support.",
    whatTheyDo: "Runs education, healthcare, protection, and emergency-response programs for children.",
    whoTheyHelp: "Children in poverty, conflict, and disaster-affected communities.",
    whySelected: "Established global network with strong child-protection and reporting standards.",
    impactExample: "Contributions of this kind have supported school access and child-nutrition programs.",
    sdgs: ["SDG 3", "SDG 4"],
    amountRaised: 96000,
    ceiling: 500000,
    registration: "Registered international NGO",
    yearsActive: 100,
    verificationNotes: "Verified via public annual reporting and international governance standards.",
  },
  {
    slug: "indian-red-cross-society",
    name: "Indian Red Cross Society",
    category: "Relief",
    status: "Active",
    shortDescription: "Supports disaster response, blood services, health programs, and humanitarian relief.",
    whatTheyDo: "Coordinates disaster response, blood services, and community health programs.",
    whoTheyHelp: "Communities affected by disasters, and patients dependent on blood-donation services.",
    whySelected: "Nationwide humanitarian infrastructure and long operating history in India.",
    impactExample: "Contributions of this kind have supported disaster-relief kits and blood-donation drives.",
    sdgs: ["SDG 1", "SDG 3"],
    amountRaised: 158000,
    ceiling: 500000,
    registration: "Registered under the Indian Red Cross Society Act",
    yearsActive: 100,
    verificationNotes: "Verified via statutory registration and public annual reporting.",
  },
  {
    slug: "akshaya-patra-foundation",
    name: "Akshaya Patra Foundation",
    category: "Nutrition",
    status: "Active",
    shortDescription: "Runs school meal programs that help children stay nourished and in classrooms.",
    whatTheyDo: "Operates large-scale school meal kitchens and nutrition programs.",
    whoTheyHelp: "School-going children in under-resourced communities across India.",
    whySelected: "Measurable nutrition and school-attendance outcomes with transparent reporting.",
    impactExample: "Contributions of this kind have funded meals that keep children in school.",
    sdgs: ["SDG 1", "SDG 4"],
    amountRaised: 267000,
    ceiling: 500000,
    registration: "Registered Indian NGO",
    yearsActive: 25,
    verificationNotes: "Verified via registration documents and public annual reporting.",
  },
  {
    slug: "teach-for-india",
    name: "Teach For India",
    category: "Education",
    status: "Active",
    shortDescription: "Builds leadership and teaching capacity to expand educational opportunity for children.",
    whatTheyDo: "Places and trains fellows as teachers in under-resourced schools.",
    whoTheyHelp: "Children in low-income communities with limited access to quality education.",
    whySelected: "Clear model, measurable classroom outcomes, and strong alumni network.",
    impactExample: "Contributions of this kind have supported fellow placements and classroom resources.",
    sdgs: ["SDG 4", "SDG 10"],
    amountRaised: 74000,
    ceiling: 500000,
    registration: "Registered Indian NGO",
    yearsActive: 15,
    verificationNotes: "Verified via registration documents and public annual reporting.",
  },
  {
    slug: "goonj",
    name: "Goonj",
    category: "Community",
    status: "Active",
    shortDescription: "Channels urban surplus into rural development, disaster relief, and community-led work.",
    whatTheyDo: "Redirects urban material surplus into rural development and disaster-relief work.",
    whoTheyHelp: "Rural and disaster-affected communities across India.",
    whySelected: "Distinctive, dignity-first development model with strong on-ground reach.",
    impactExample: "Contributions of this kind have supported disaster-relief material distribution.",
    sdgs: ["SDG 1", "SDG 10"],
    amountRaised: 139000,
    ceiling: 500000,
    registration: "Registered Indian NGO",
    yearsActive: 25,
    verificationNotes: "Verified via registration documents and public annual reporting.",
  },
  {
    slug: "pratham",
    name: "Pratham",
    category: "Education",
    status: "Active",
    shortDescription: "Works to improve learning outcomes and access to education for children across India.",
    whatTheyDo: "Runs learning-outcome and foundational-literacy programs across India.",
    whoTheyHelp: "Children in under-resourced schools and communities.",
    whySelected: "Data-driven education work with a long, well-documented track record.",
    impactExample: "Contributions of this kind have supported foundational literacy and numeracy programs.",
    sdgs: ["SDG 4"],
    amountRaised: 203000,
    ceiling: 500000,
    registration: "Registered Indian NGO",
    yearsActive: 30,
    verificationNotes: "Verified via registration documents and public annual reporting.",
  },
  {
    slug: "cry",
    name: "CRY",
    category: "Children",
    status: "Active",
    shortDescription: "Focuses on child rights, education, protection, healthcare, and child participation.",
    whatTheyDo: "Supports child-rights, education, protection, and healthcare programs.",
    whoTheyHelp: "Children whose rights to education, health, and protection are at risk.",
    whySelected: "Rights-based approach with strong grassroots partner network.",
    impactExample: "Contributions of this kind have supported child-protection and education initiatives.",
    sdgs: ["SDG 4", "SDG 10"],
    amountRaised: 88000,
    ceiling: 500000,
    registration: "Registered Indian NGO",
    yearsActive: 45,
    verificationNotes: "Verified via registration documents and public annual reporting.",
  },
  {
    slug: "helpage-india",
    name: "HelpAge India",
    category: "Elder Care",
    status: "Active",
    shortDescription: "Supports disadvantaged elderly people through healthcare, livelihoods, and advocacy.",
    whatTheyDo: "Runs healthcare, livelihood, and advocacy programs for elderly people.",
    whoTheyHelp: "Disadvantaged elderly individuals, particularly those without family support.",
    whySelected: "Dedicated focus on an under-served cause area with long operating history.",
    impactExample: "Contributions of this kind have supported mobile healthcare units for elderly patients.",
    sdgs: ["SDG 1", "SDG 10"],
    amountRaised: 61000,
    ceiling: 500000,
    registration: "Registered Indian NGO",
    yearsActive: 40,
    verificationNotes: "Verified via registration documents and public annual reporting.",
  },
  {
    slug: "the-banyan",
    name: "The Banyan",
    category: "Mental Health",
    status: "Active",
    shortDescription: "Works with people experiencing homelessness and mental health challenges.",
    whatTheyDo: "Provides mental healthcare and rehabilitation support, including for people facing homelessness.",
    whoTheyHelp: "People experiencing mental health challenges and homelessness.",
    whySelected: "Specialist, dignity-focused approach in a cause area with limited coverage.",
    impactExample: "Contributions of this kind have supported emergency care and rehabilitation programs.",
    sdgs: ["SDG 3", "SDG 10"],
    amountRaised: 45000,
    ceiling: 500000,
    registration: "Registered Indian NGO",
    yearsActive: 30,
    verificationNotes: "Verified via registration documents and public annual reporting.",
  },
];

export function getCharityBySlug(slug: string): Charity | undefined {
  return charities.find((charity) => charity.slug === slug);
}

export const sdgDescriptions: Record<string, string> = {
  "SDG 1": "No Poverty — livelihood and social-support programmes.",
  "SDG 3": "Good Health and Well-Being — hospitals, healthcare, and medical assistance.",
  "SDG 4": "Quality Education — schools, scholarships, and educational initiatives.",
  "SDG 10": "Reduced Inequalities — disability, inclusion, and disadvantaged communities.",
  "SDG 13": "Climate Action — environmental initiatives.",
  "SDG 14": "Life Below Water — marine conservation.",
  "SDG 15": "Life on Land — wildlife, animal welfare, and conservation.",
};
